"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useAuthStore } from "@/store/authStore";

// Assuming you have these in your project like the dashboard
import Navbar from "../../../components/Navbar"; 
import Footer from "../../../components/Footer";

import Tabs from "./components/Tabs";
import ModulesTab from "./components/ModulesTab";
import OutcomesTab from "./components/OutcomesTab";
import ResourcesTab from "./components/ResourcesTab";
import QuestionsTab from "./components/QuestionsTab";
import { Printer } from "lucide-react";

const API = "http://localhost:5001";

export default function SyllabusPage() {
  const { id } = useParams();
  const router = useRouter();
  const { token, hasHydrated } = useAuthStore();

  const [tab, setTab] = useState("modules");
  const [modules, setModules] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!hasHydrated || !token) return;

    const fetchModules = async () => {
      setLoading(true);
      try {
        const res = await fetch(`${API}/api/syllabus/${id}/modules`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (data.success) setModules(data.modules);
      } catch {
        setModules([]);
      } finally {
        setLoading(false);
      }
    };

    fetchModules();
  }, [id, token, hasHydrated]);

  if (!hasHydrated) return null;

  const handlePrint = () => {
    if (!modules || modules.length === 0) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Modules Print - ${new Date().toLocaleDateString()}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; max-width: 900px; margin: 2rem auto; padding: 2rem; }
            h1 { color: #5da8bd; border-bottom: 3px solid #BBDCE5; padding-bottom: 10px; }
            .module { background: #ECEEDF; border-left: 4px solid #5da8bd; padding: 20px; margin-bottom: 24px; border-radius: 8px; }
            .module-title { font-size: 1.2rem; font-weight: bold; color: #6b8288; margin-bottom: 10px; }
            .module-content { color: #555; line-height: 1.65; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #D9C4B0; text-align: center; color: #6b8288; font-size: 12px; }
            @media print { .module { page-break-inside: avoid; } }
          </style>
        </head>
        <body>
          <h1> Extracted Modules</h1>
          <div><strong>Date:</strong> ${new Date().toLocaleString()}</div>
          <div style="margin: 16px 0;"><strong>Total Modules:</strong> ${modules.length}</div>
          ${modules
            .map(
              (mod, idx) => `
              <div class="module">
                <div class="module-title">${mod.title || `Module ${idx + 1}`}</div>
                <div class="module-content">${mod.content || 'No content available'}</div>
              </div>
            `
            )
            .join('')}
          <div class="footer">Generated by ModuLearn | AI-powered Syllabus Extraction</div>
        </body>
      </html>
    `;
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };



  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 flex flex-col">
      <Navbar />

      <main className="p-8 max-w-6xl mx-auto w-full flex-grow">
        {/* Header matching Dashboard style */}
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-800">
              Syllabus Details
            </h1>
            <p className="text-gray-500 mt-2">
              Explore modules, outcomes, and resources
            </p>
          </div>

<div className="flex items-center gap-3">
          <button
            onClick={() => router.push("/dashboard")}
            className="bg-white border text-gray-600 px-5 py-2 rounded-lg shadow-sm hover:bg-gray-50 transition"
          >
            ← Back to Dashboard
          </button>
          <button
                      onClick={handlePrint}
                      className="flex items-center justify-center gap-1.5 px-3 py-2 bg-[#5da8bd] text-white rounded-lg hover:bg-[#91bcc6] transition-colors text-sm w-fit"
                      title="Print all modules"
                    >
                      <Printer className="w-4 h-4" />
                      <span>Print Modules</span>
                    </button>
                    </div>
        </div>

        {/* Content Container */}
        <div className="bg-white/50 backdrop-blur-sm rounded-2xl border p-6 shadow-sm min-h-[500px]">
          <Tabs tab={tab} setTab={setTab} />

          <div className="mt-6">
            {loading && <p className="text-gray-500 animate-pulse py-10 text-center">Loading syllabus data...</p>}

            {!loading && tab === "modules" && <ModulesTab modules={modules} />}
            {!loading && tab === "co" && <OutcomesTab syllabusId={id as string} />}
            {!loading && tab === "resources" && <ResourcesTab modules={modules} />}
            {!loading && tab === "questions" && <QuestionsTab />}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}